version: "3.9"

services:
  deliveryfood-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "13306:3306"
    networks:
      - deliveryfood-network
  
  deliveryfood-api:
    image: deliveryfood-api:0.0.1-SNAPSHOT
    command: [ "/wait-for-it.sh", "-t", "30", "deliveryfood-mysql:3306", "--", "java", "-jar", "api.jar" ]
    environment:
      DB_HOST: deliveryfood-mysql
      SPRING_PROFILES_ACTIVE: development
    ports:
      - "8080:8080"
    networks:
      - deliveryfood-network
    depends_on:
      - deliveryfood-mysql

networks:
  deliveryfood-network:
    driver: bridge
    